### ISSUE TITLE
SSS | action woocommerce_json_search_products_and_variations is not working ...

### ISSUE THREAD

**Issue by marinblu** [superspeedyplugins/issue-tracker#17]
I had to disable "Override WooCommerce wp-admin Product Search" in order action "woocommerce_json_search_products_and_variations" to work!

1.Login at our server, check dm ...
2.Activate "Override WooCommerce wp-admin Product Search"
3.Edit or add a product
4.Try to add a product at bought together that is using woocommerce_json_search_products_and_variations ...

**Comment by dhilditch** [comment]
A recent update by me to override WooCommerce Product Search has created this bug.

It would be useful if we could have two functions here - the new fast one and the original one. The original one from the older code was more compatible with JSON and API calls etc whilst the newer one has more functionality and speed for the actual edit.php Product List.

1. Find the edit in the readme.txt file or github commits where I edited the WooCommerce product override function
2. Copy the old override function I had, rename it so we don't have duplicate function names
3. Add some logic so that my new code only ever runs for the main query on the edit.php page when viewing the products list otherwise the older override runs.

**Comment by hmkayani** [comment]
Now, Ajax search functionality on the product edit page which was not working when "Override WooCommerce wp-admin Product Search" was checked is fixed, results are displayed.

**Comment by dhilditch** [comment]
This issue fixed in 4.36
