### ISSUE TITLE
Option to show filters AFTER search results displayed for SSF

### ISSUE THREAD

**Issue by RexHavoc69** [superspeedyplugins/issue-tracker#172]
1. Our website is large and as we add more filters it impacts the search speed.
2. I would like an option so the users can select to 'show filters' after the search results are displayed. Search results will then be fast to display and if the user wants the filters to drill down on the results then there is still the option to load them separately.
3. This option would also be handy for category result pages if it improves the load speed.

**Comment by dhilditch** [comment]
![image](https://github.com/user-attachments/assets/72d5b414-41ce-4105-9241-44e650486f0a)

In the image you can see our Display on Search Results option.

Add an extra option in here:

"Show but delay execution"

Make it so that this option is disabled if the widget does not have a Display Container set, otherwise it won't make sense.

Currently - if there is a display container, we still need to run the underlying code to check if we should even display the container. In this new code, if the widget says Show but delay execution, then we would always display the container on the search results with the related ajax class (you can find the ajax class inside the tax widget).

i.e. this should be quite simple - when displaying a container like this, we can avoid running the fast cats queries and the walktree function until a user clicks the container.

Summary: with this option, the container should always be displayed and the first page load the actual SQL and walktree function will not run on initial page load, instead they will run through the ajax call using the existing ajax callback code. It should be a simple matter of avoiding the fastcatsql, the walktree, but making sure the right ajax classes are on the container to enable the other code.

**Comment by dhilditch** [comment]
I've ended up reverted this code out of the master branch as it's quite broken and a bit of a mess.

I'll code up the solution myself so it re-uses my existing ajax code.

**Comment by dhilditch** [comment]
Fixed in 5.87
