### ISSUE TITLE
Variation Additional Images Appearance Problem

### ISSUE THREAD

**Issue by ozteeprint** [superspeedyplugins/issue-tracker#32]
After External Images 3.04 was upgraded, the variation images appeared incorrectly.

For example: This below product chosen color was Blue, but the additional images were black. It was incorrect.  They should be blue. However, on the backend product, I confirmed that the additional images were blue. I think main image and its variation images overrides the other color attributes.  See the example image

![image](https://github.com/superspeedyplugins/issue-tracker/assets/154464714/4526ecb4-4a44-401e-a5f5-c4425e79cf1f)

**Comment by dhilditch** [comment]
This is similar problem to #14 where either we need to intercept the Woo request when all variation options are entered and a variation change event is triggered so we can return the thumbs and the images, right now only the featured image for the variation seems to be getting returned. This would be most compatible way.

Other way is to parse through the current thumbs and figures and replace them one by one and if there are surplus thumbs in the existing page, delete them, and if there are extra images in the new variation, add them. This will fix the other issue that comes up using our JS where we end up breaking some of the JS that has been added to the gallery (owl or slick or whatever gallery)

**Comment by dhilditch** [comment]
Fixed in 3.07 - will still need to identify other carousel triggers in other main themes, but for now this is working quite well.

If a theme is not handled, the variation gallery will still appear and be clickable, but it will not behave like the carousel from the main parent product.

I searched through Woodmart for .woocommerce-product-gallery and found a function I could call, other themes will be similar.
