### ISSUE TITLE
SSF | postmeta range from with out max is not working

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#36]
**Describe the bug**
If you set a postmeta range with this set up: 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/659767cb-329f-4ffe-8fb3-23a7a939b279)
 
and then try at frontend something like this: 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/ab89ee91-0edd-45a4-b011-d3d69eb0f6fd)

it is not working, because the max is not selected

**Expected behavior**
It should display everything from 10 and above

**Comment by gfarma** [comment]
Same for price slider

**Comment by dhilditch** [comment]
@voodoo911 can you please fix the code re: max range in the post meta range filters - there are two parts to fix:

1. If a user does not enter a max price, &max_price= (empty string) should not appear, e.g. if I enter 10 in min price and nothing in the max price, i get a URL like this: http://davelocal/shop/?minprice=10&maxprice=
-- please not that the URL parameters can vary wildly, it's not just for maxprice, any postmeta value can be filtered but this should not complicate matters, you just need to find the JS code attached to the APPLY button and fix it so that it doesn't include maxprice if that box is empty.
2. Do the same for min price - if a user enters only a max price (or max value of whatever meta key) then the min price param should not be added
3. In the PHP code that reads the range values, it has a lookup table to convert ?maxprice to _price or whatever meta_key, if maxprice is empty, ignore that parameter (it's currently being treated as 0). Similarly for minprice, if the URL param is empty, don't add the minprice to the DB query.

**Comment by dhilditch** [comment]
Fixed in 5.17
