### ISSUE TITLE
Filter options showing that do not exist

### ISSUE THREAD

**Issue by RexHavoc69** [superspeedyplugins/issue-tracker#8]
**Describe the bug**
Super Speedy Filters...

A Filter provides a list of options but when one of those options is selected there are no results.

**To Reproduce**
Go to: https://pp.co.nz/memory/8tb/6tb?expand_pa_memory=1&s=ssd+m.2+sata 
The Memory/Storage Capacity filter suggests there are 6TB and 8TB options but none show in the results.

**Expected behavior**
I would expect to see 6TB and 8TB SSDs listed in the results.
or, the filter should not give these options.

**Screenshots**
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/45a0c563-7798-4176-9980-f0ef21657005)
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/0b1bb19d-8e9d-423b-9c0b-d9bde2551b08)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Comment by dhilditch** [comment]
Please check if you have maybe added this to your wp-config?

**Comment by dhilditch** [comment]
Check if you added this to wp-config:

`define('SSF_MAKE_FILTERS_BE_FILTERED_BY_SEARCH', false);`

If so, delete it and then your filters will be filtered by search.

Otherwise, ensure the RAM storage filter is set to respect other filters.

If this doesn't help, please contact me on Discord. I am not certain this is a bug yet.

**Comment by RexHavoc69** [comment]
wp-config does not have that entry.
Memory Storage/Capacity is set to respect other filters.
Can do Discord at another time. Its quite busy right now.
